name: Issue Report
title: 'Issue: '
assignees:
    - strbit
labels:
    - Issue
description: Report an issue related to the code of this project.
body:
    - type: markdown
      attributes:
          value: |
              ## You're about to create a bug report within a Jarsoft repository.

              Make sure your issue is descriptive & concise. Discursive issues will most likely be closed by the team. Feel free to use external guides and resources (such as [Stackoverflow's suggestions](https://stackoverflow.com/help/how-to-ask)) to assist in writing a well-formed issue.

              Before you start, be sure you are aware of the following points:
              * Avoid duplicating any existing issues which already track or resolve your problem.
              * Aim to find a descriptive and precise title for your bug report.

              *By creating the issue, the organization's [Code of Conduct](https://github.com/jarsft/.github/blob/production/CODE_OF_CONDUCT.md) & [Contributing Guide](https://github.com/jarsft/.github/blob/production/CONTRIBUTING.md) documents apply.*
    - type: textarea
      id: description
      attributes:
          label: Describe the issue
          description: Provide a clear & concise description of what the bug is.
          placeholder: Description of the bug...
      validations:
          required: true
    - type: textarea
      id: expected
      attributes:
          label: Expected behaviour
          description: Provide a clear & concise description of what should've happened.
          placeholder: What should've happened...
      validations:
          required: true
    - type: textarea
      id: reproduction
      attributes:
          label: Issue Reproduction
          description: A minimal reproduction is **required**, otherwise the issue might be closed.
          placeholder: |
              A description of how to reproduce this bug...

              1. With this configuration...
              2. Run...
              3. Encounter error...
      validations:
          required: true
    - type: textarea
      id: system
      attributes:
          label: Workbench information
          description: |
              ## Run the following command & paste it's output here.

              *If you're reporting an issue with a workflow, ONLY state what architecture (e.x. ubuntu-latest) the workflow runs on.*

              Keep in mind that you need to have [`Node.js`](https://nodejs.org) & [`npm`](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm) installed in order to run this script. Make sure you run this script in the failing environment. If you can't supply the workbench information for whatever reason, please state why.

              `npx envinfo --system --browsers --binaries`
          render: markdown
          placeholder: Your system, browsers & binaries...
      validations:
          required: true
    - type: textarea
      id: logs
      attributes:
          label: Stack Logs
          description: |
              Please provide a relevant log output.

              Be sure to **remove any sensitive information** such as passwords, tokens, etc.

              If you have a lengthy log message, please attach the file in the `Additional information` section.
          placeholder: Logs which contain the error...
      validations:
          required: true
    - type: dropdown
      id: severity
      attributes:
          label: Priority Level
          description: Select the priority level which best fits the issue.
          multiple: false
          options:
              - Critical [P1] (Crashes, Data Loss, Security Risks)
              - High [P2] (Performance issues, Malfunctions)
              - Medium [P3] (Minor issues)
              - Low [P4] (Cosmetic flaws, typos)
              - Trivial [P5] (Minor inconsistencies)
      validations:
          required: true
    - type: textarea
      id: context
      attributes:
          label: Additional information
          description: |
              Feel free to provide additional information which may help resolve this issue.

              It might include screenshots, configurations, or log outputs.
          placeholder: Additional information related to the issue...
      validations:
          required: false
    - type: checkboxes
      id: checkboxes
      attributes:
          label: Submission checklist
          description: Before submitting the issue, please make sure you do the following
          options:
              - label: Follow the [Code of Conduct](https://github.com/jarsft/.github/blob/production/CODE_OF_CONDUCT.md)
                required: true
              - label: Read the [Contribution Guide](https://github.com/jarsft/.github/blob/production/CONTRIBUTING.md)
                required: true
              - label: Check that no issue that reports the same bug exists.
                required: true
              - label: Check that this is a concrete bug.
                required: true
              - label: The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
                required: true
              - label: Double-checked that the issue is descriptive & concise.
                required: true
    - type: checkboxes
      id: contributions
      attributes:
          label: Optional contributions
          description: Check the boxes if you have possible solutions or finished code fixes.
          options:
              - label: I am willing to submit a PR to fix this issue.
              - label: I am willing to submit an unfinished/unstable PR. (failing tests, etc.)
