blank_issues_enabled: true
contact_links:
    - name: Contribution Guidelines
      url: https://github.com/jarsft/.github/blob/production/CONTRIBUTING.md
      about: Read through these guidelines prior to contributing.
    - name: How to & why submit reproductions?
      url: https://stackoverflow.com/help/minimal-reproducible-example
      about: We require reproductions to be submitted in order to file a project issue.
