name: Feature Request
title: 'Feature: '
assignees:
    - strbit
description: Propose a new feature to add to the project.
body:
    - type: markdown
      attributes:
          value: |
              ## You're about to create a feature request within a Jarsoft repository.

              Make sure your issue is descriptive & concise. Discursive issues will most likely be closed by the team. Feel free to use external guides and resources (such as [Stackoverflow's suggestions](https://stackoverflow.com/help/how-to-ask)) to assist in writing a well-formed issue.

              Before you start, be sure you are aware of the following points:
              * Avoid duplicating any existing feature requests which already track or implement your request.
              * Aim to find a descriptive and precise title for your bug report.

              *By creating the issue, the organization's [Code of Conduct](https://github.com/jarsft/.github/blob/production/CODE_OF_CONDUCT.md) & [Contributing Guide](https://github.com/jarsft/.github/blob/production/CONTRIBUTING.md) documents apply.*
    - type: textarea
      id: description
      attributes:
          label: Describe the problem
          description: Provide a concise and clear description of the problem you wish to solve.
          placeholder: I want [goal/wish] so that [benefit]...
      validations:
          required: true
    - type: textarea
      id: suggestion
      attributes:
          label: Suggested solution
          description: Describe how the feature could be implemented into the project.
          placeholder: Proposed steps to implement this feature...
      validations:
          required: true
    - type: textarea
      id: context
      attributes:
          label: Additional information
          description: Feel free to provide additional information which may help implement this feature.
          placeholder: Additional information related to the feature...
      validations:
          required: false
    - type: checkboxes
      id: checkboxes
      attributes:
          label: Submission checklist
          description: Before submitting the feature request, please make sure you do the following
          options:
              - label: Follow the [Code of Conduct](https://github.com/jarsft/.github/blob/production/CODE_OF_CONDUCT.md)
                required: true
              - label: Read the [Contribution Guide](https://github.com/jarsft/.github/blob/production/CONTRIBUTING.md)
                required: true
              - label: Check that no issue that requests the same feature exists.
                required: true
