name: Upload Branding Assets
on:
    workflow_dispatch:
        inputs:
            bucket:
                description: Upload to specific bucket?
                required: true
    push:
        paths:
            - specs/**/*
jobs:
    upload:
        name: Upload Assets
        runs-on: ubuntu-latest
        steps:
            - name: Check-out Repository
              uses: actions/checkout@v4

            - name: Upload Assets
              uses: shallwefootball/s3-upload-action@v1.3.0
              with:
                  aws_key_id: ${{ secrets.BRANDING_AWS_KEY }}
                  aws_secret_access_key: ${{ secrets.BRANDING_AWS_SECRET_KEY }}
                  aws_bucket: ${{ inputs.bucket || vars.AWS_STORAGE_BUCKET }}
                  source_dir: branding
                  destination_dir: branding
                  # endpoint: ''
    notify:
        name: Notify Upload
        runs-on: ubuntu-latest
        needs: upload
        steps:
            - name: Notify Success
              uses: rjstone/discord-webhook-notify@v1
              if: success()
              with:
                  webhookUrl: ${{ secrets.BRANDING_WEBHOOK_URL }}
                  severity: info
                  color: '#88af2c'
                  username: Jarsoft Branding
                  details: |
                      Branding assets updated via a new **${{ github.event_name }}** event.
                      **See Amazon storage bucket for details.**

                      [→ Debug this workflow](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
