name: Upload Branding Assets
on:
    workflow_dispatch:
        inputs:
            bucket:
                description: Upload all branding assets to a specific bucket?
                required: false
            region:
                type: choice
                description: Select an AWS region to deploy all branding assets to.
                options:
                    - us-east-1
                default: 'us-east-1'
                required: true
    push:
        paths:
            - branding/**/*
jobs:
    upload:
        name: Upload Assets
        runs-on: ubuntu-latest
        steps:
            - name: Check-out Repository
              uses: actions/checkout@v4

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              id: credentials
              with:
                audience: sts.amazonaws.com
                aws-region: us-east-3
                role-to-assume: ${{ secrets.BRANDING_ROLE_ARN }}
                role-duration-seconds: 1800
                role-session-name: ${{ secrets.BRANDING_ROLE_SESSION }}
                output-credentials: true
                unset-current-credentials: true

            - name: Upload Assets
              uses: shallwefootball/s3-upload-action@v1.3.0
              with:
                  aws_key_id: ${{ steps.credentials.outputs.aws-access-key-id }}
                  aws_secret_access_key: ${{ steps.credentials.outputs.aws-secret-access-key }}
                  aws_bucket: ${{ inputs.bucket || vars.AWS_STORAGE_BUCKET }}
                  source_dir: branding
                  destination_dir: branding
    notify:
        name: Notify Upload
        runs-on: ubuntu-latest
        needs: upload
        steps:
            - name: Notify Success
              uses: rjstone/discord-webhook-notify@v1
              if: success()
              with:
                  webhookUrl: ${{ secrets.BRANDING_WEBHOOK_URL }}
                  severity: info
                  details: |
                      New branding assets were uploaded via a **${{ github.event_name }}** event.
                      **Please see the `${{ inputs.bucket || vars.AWS_STORAGE_BUCKET }}` bucket for details.**

                      [→ Debug this workflow](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
                  username: Jarsoft Branding
                  color: '#88af2c'
                  avatarUrl: https://storage.jar.run/branding/light/mark.png
