name: Require CLA Agreement
on:
    workflow_dispatch:
    issue_comment:
        types:
            - created
    pull_request_target:
        types:
            - opened
            - closed
            - synchronize
permissions:
    actions: write
    contents: write
    pull-requests: write
    statuses: write
jobs:
    assistant:
        name: Start CLA Assistant
        runs-on: ubuntu-latest
        if: (github.event.issue.pull_request && (github.event.comment.body == 'recheck' || github.event.comment.body == ${{ vars.CLA_SIGN_COMMENT }}) || github.event_name == 'pull_request_target')
        steps:
            - name: App Token
              uses: actions/create-github-app-token@v1
              id: token
              with:
                  app-id: ${{ vars.CLA_APP_ID }}
                  private-key: ${{ secrets.CLA_APP_PRIVATE_KEY }}
                  owner: ${{ github.repository_owner }}

            - name: CLA Assistant
              uses: entropyxyz/contributor-assistant-github-action@exemptRepoOrgMembers # contributor-assistant/github-action@v2.5.0
              env:
                  GITHUB_TOKEN: ${{ steps.token.outputs.token }}
                  PERSONAL_ACCESS_TOKEN: ${{ steps.token.outputs.token }}
              with:
                  path-to-signatures: signatures/version1.json
                  path-to-document: https://github.com/jarsft/.github/blob/production/agreements/CLA.md
                  branch: production
                  allowlist: bot*

                  # This action input does not exist yet in the official action and is part of a proposed change.
                  # Revert to the original action if https://github.com/contributor-assistant/github-action/pull/157 is successfully merged.
                  exemptRepoOrgMembers: true

                  remote-organization-name: jarsft
                  remote-repository-name: signatures
                  create-file-commit-message: 'feat: created file for CLA signatures'
                  signed-commit-message: 'chore: `$contributorName` has signed the CLA in `$owner/$repo#${{ github.event.number }}`'
                  # signed-empty-commit-message: 'chore: empty commit'
                  # create-file-commit-message: 'chore: create contributors file'
                  custom-notsigned-prcomment: |
                      We've received your pull-request, but it looks like this may be your first contribution to a Jarsoft project. Before we can merge your pull-request, you'll need to sign a [Contributor License Agreement](https://en.wikipedia.org/wiki/Contributor_License_Agreement) allowing Jarsoft (or for public repositories, the public) to use your changes.

                      * See the [CLA document here](https://github.com/jarsft/.github/blob/production/agreements/CLA.md) for details.

                      Reply with the phrase at the bottom of this comment to sign the CLA & to proceed with the merge. If you've already signed the CLA, comment `recheck`, the workflow will automatically re-run & re-check your signature status.
                  # custom-pr-sign-comment: 'I have read the CLA document and hereby sign & accept the CLA agreement'
                  custom-allsigned-prcomment: '**CLA Status** - All contributors have signed the CLA.'
                  # lock-pullrequest-aftermerge: false
                  # use-dco-flag: true - If you're using a DCO agreement instead of a CLA.
