name: Close Stale PRs & Issues
on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * *'
permissions:
    issues: write
    pull-requests: write
jobs:
    stale:
        name: Detect Stale
        runs-on: ubuntu-latest
        steps:
            - uses: actions/stale@v9
              with:
                  # repo-token: -
                  days-before-stale: ${{ vars.STALE_INACTIVITY_PERIOD }}
                  # days-before-issue-stale: -
                  # days-before-pr-stale: -
                  days-before-close: ${{ vars.STALE_CLOSURE_PERIOD }}
                  # days-before-issue-close: -
                  # days-before-pr-close: -
                  stale-issue-message: ${{ format(vars.STALE_BASE_MESSAGE, 'issue', vars.STALE_INACTIVITY_PERIOD, vars.STALE_INACTIVITY_PERIOD) }}
                  stale-pr-message: ${{ format(vars.STALE_BASE_MESSAGE, 'pull-request', vars.STALE_INACTIVITY_PERIOD, vars.STALE_CLOSURE_PERIOD) }}
                  # close-issue-message: -
                  # close-pr-message: -
                  # stale-issue-label: Stale
                  # close-issue-label: -
                  # close-issue-reason: not_planned
                  # stale-pr-label: Stale
                  # close-pr-label: -
                  exempt-issue-labels: 'Keep Alive'
                  exempt-pr-labels: 'Keep Alive'
                  # only-labels: -
                  # only-issue-labels: -
                  # only-pr-labels: -
                  # any-of-labels: -
                  # any-of-issue-labels: -
                  # any-of-pr-labels: -
                  # operations-per-run: 30
                  # remove-stale-when-updated: true
                  # remove-issue-stale-when-updated: -
                  # remove-pr-stale-when-updated: -
                  # labels-to-add-when-unstale: -
                  # labels-to-remove-when-unstale: -
                  # debug-only: false
                  # ascending: false
                  # start-date: -
                  # delete-branch: false
                  # exempt-milestone: -
                  # exempt-issue-milestones: -
                  # exempt-pr-milestones: -
                  # exempt-all-milestones: false
                  # exempt-all-issue-milestones: -
                  # exempt-all-pr-milestones: -
                  exempt-assignees: bot*
                  # exempt-issue-assignees: -
                  # exempt-pr-assignees: -
                  # exempt-all-assignees: false
                  # exempt-all-issue-assignees: -
                  # exempt-all-pr-assignees: -
                  # exempt-draft-pr: false
                  # enable-statistics: true
                  # ignore-updates: false
                  # ignore-issue-updates: -
                  # ignore-pr-updates: -
                  # include-only-assigned: false
